#!/bin/zsh
# Assemble placeholders and build PDFs with pandoc + tectonic.
#   {{table:NAME}}            -> tables/NAME.md (generated by `calc-bounds paper`)
#   {{file:PATH}}             -> contents of PATH (relative to paper/)
#   {{section:PATH|HEADING}}  -> the section of PATH under HEADING, up to the next heading
set -euo pipefail
cd "$(dirname "$0")"
mkdir -p build
# arXiv: one document = manuscript + supplement as an appendix.
{
  cat manuscript.md
  printf '\n\n\\clearpage\n\\appendix\n\n# Supplementary material\n\n'
  sed '1,/^---$/{/^---$/!d;};1,/^---$/d' supplement.md | sed 's/^## /## /'
} > arxiv.md
for doc in manuscript supplement arxiv; do
  python3 - "$doc" <<'PY'
import re, sys
from pathlib import Path
doc = sys.argv[1]
text = Path(f"{doc}.md").read_text()
def section(path, heading):
    src = Path(path).read_text()
    start = src.index(heading) + len(heading)
    level = heading.split()[0]
    m = re.search(rf"^{re.escape(level)} ", src[start:], flags=re.M)
    return src[start : start + m.start()] if m else src[start:]
def repl(m):
    kind, arg = m.group(1), m.group(2)
    if kind == "table":
        return Path(f"tables/{arg}.md").read_text()
    if kind == "file":
        return Path(arg).read_text()
    path, heading = arg.split("|", 1)
    return section(path, heading)
out = re.sub(r"\{\{(table|file|section):([^}]+)\}\}", repl, text)
# Pandoc needs a blank line before a list that follows a paragraph line.
lines, fixed, in_code = out.split("\n"), [], False
for line in lines:
    if line.startswith("```"):
        in_code = not in_code
    is_item = re.match(r"^\s*(- |\d+\. )", line) is not None
    prev = fixed[-1] if fixed else ""
    prev_item = re.match(r"^\s*(- |\d+\. )", prev) is not None or prev.startswith("  ")
    if not in_code and is_item and prev.strip() and not prev_item and not prev.startswith("|"):
        fixed.append("")
    fixed.append(line)
out = "\n".join(fixed)
Path(f"build/{doc}.md").write_text(out)
PY
  pandoc "build/$doc.md" -o "$doc.pdf" --pdf-engine=tectonic \
    -V geometry:margin=1.8cm -V fontsize=9pt -V linestretch=1.1 -V colorlinks=true \
    -V mainfont="Helvetica" -V monofont="Menlo" --resource-path=.:figures:build \
    2> "build/$doc.log" || { tail -20 "build/$doc.log"; exit 1; }
  pandoc "build/$doc.md" -s -o "build/$doc.tex" --resource-path=.:figures:build
  echo "built paper/$doc.pdf (+ build/$doc.tex for arXiv)"
done

# arXiv source package: tex + figures, flat paths.
rm -rf build/arxiv && mkdir -p build/arxiv/figures
# arXiv compiles with pdfLaTeX: declare the non-ASCII symbols we use (no-op under XeTeX).
python3 - <<'PY'
from pathlib import Path
tex = Path("build/arxiv.tex").read_text(encoding="utf8")
decl = r"""\ifPDFTeX
\DeclareUnicodeCharacter{2265}{\ensuremath{\geq}}
\DeclareUnicodeCharacter{2264}{\ensuremath{\leq}}
\DeclareUnicodeCharacter{00D7}{\ensuremath{\times}}
\DeclareUnicodeCharacter{2192}{\ensuremath{\rightarrow}}
\DeclareUnicodeCharacter{00B5}{\ensuremath{\mu}}
\DeclareUnicodeCharacter{00B0}{\ensuremath{^{\circ}}}
\DeclareUnicodeCharacter{00B1}{\ensuremath{\pm}}
\DeclareUnicodeCharacter{2212}{\ensuremath{-}}
\fi
"""
tex = tex.replace("\\begin{document}", decl + "\\begin{document}", 1)
Path("build/arxiv/main.tex").write_text(tex, encoding="utf8")
PY
cp figures/*.pdf figures/figS5_reliability.png build/arxiv/figures/
(cd build/arxiv && zip -qr ../../arxiv_source.zip .)
echo "built paper/arxiv_source.zip (upload to arXiv) and paper/arxiv.pdf (what it should look like)"
